name: Update Status

on:
  watch:
    types: [started]
  schedule:
    - cron: "*/39 * * * *"
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v2
      with:
        chrome-version: stable
        install-chromedriver: true
    
    - name: Build
      run: |
        python ./run/updater.py
    
    - name: Package downloaded files
      run: |
        ls
        zip -r results_${{ github.run_number }}.zip ./result/
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: result-${{ github.run_number }}
        path: results_${{ github.run_number }}.zip
